# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: Build_Job
    steps:
      - script: echo "Building..."
- stage: Test
  jobs:
  - job: Test_Job_1
    steps:
      - script: echo "Running Test 1..."
  - job: Test_Job_2
    steps:
      - script: echo "Running Test 2..."
- stage: Deploy
  
  jobs:
  - job: 
    steps:
      - script: echo "Deploying..."